# Use the official Prometheus image as the base
FROM prom/prometheus:latest

# Set the working directory
WORKDIR /etc/prometheus

# Copy Prometheus configuration file
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Copy any additional rules (optional)
COPY alert_rules.yml /etc/prometheus/alert_rules.yml

# Expose Prometheus default port
EXPOSE 9090

# Start Prometheus
CMD [ "--config.file=/etc/prometheus/prometheus.yml"]



